### PR TITLE
Fix/294 sbt signature verification

### LINKED ISSUE #294: `vda-sbt-client` signature verification fails
When attempting to sign a SBT request, the following error is returned:

`Failed to claim SBT: Data is not signed by a valid signing DID`

### PR DESCRIPTION
**Pull request by ITStar10**
Closes #294

These are the changes made:

- Updated `isSBTClaimed()` function
- Added `getClaimedSBTList()` function
- Updated test code

This ensures that anyone can request information about claimed SBT's, not just the owner.

The original issue has signature verification failing. This was fixed in the tests by updating `getSignerInfo()` method to correctly generate the signer info.

### CODE REVIEW

File: packages/vda-sbt-client/src/blockchain/config.ts [hunk 1]
```diff
@@ -2,8 +2,8 @@
 export const CONTRACT_ADDRESSES: Record<string, string | null> = {
     mainnet: null,
     "0x89": null,
-    testnet: "0x7201189556bAF5B58b74FDf99C1957A064B87548",
```
Comment (ITStar10) [inline packages/vda-sbt-client/src/blockchain/config.ts:5]: Contract updated & deployed. Replaced with new address.

File: packages/vda-sbt-client/test/blockchain-api.test.ts [hunk 2]
```diff
@@ -19,11 +33,90 @@ const createBlockchainAPI = (did: any) => {
...
+        sbtType,
+        uniqueId,
+        sbtURI,
+        receiverAddress.toLowerCase(),
+        signedData,
+        signedProof
+    )
+}
+
+const createTestDataIfNotExist = async (
```
Comment (ITStar10) [inline packages/vda-sbt-client/test/blockchain-api.test.ts:62]: This function mint & burn SBTs for tests. This can be run only once after the contract deployed.

File: packages/vda-sbt-client/test/blockchain-api.test.ts [hunk 3]
```diff
@@ -19,11 +33,90 @@ const createBlockchainAPI = (did: any) => {
...
+    trustedSigner: InterfaceDID, 
+    blockchainApi: VeridaSBTClient,
+    keyring: Keyring,
+    signedProof: string
+    ) => {
+    const orgTotalSupply = parseInt(await blockchainApi.totalSupply())
+    if (orgTotalSupply > 0) return;
```
Comment (ITStar10) [inline packages/vda-sbt-client/test/blockchain-api.test.ts:69]: As you can see, if there were minted transaction before, this function'd not continue to run.

File: packages/vda-sbt-client/test/utils.ts [hunk 4]
```diff
@@ -168,4 +162,24 @@ export async function getNetwork(privateKey): Promise<{
...
+}
+
+/**
+ * Return keyring & signedProof for given trusted signer
+ * @param privateKey private key of trusted signer
+ */
+export async function getSignerInfo(privateKey: string): Promise<[
+  keyring: Keyring,
+  signedProof: string
+]> {
```
Comment (ITStar10) [inline packages/vda-sbt-client/test/utils.ts:174]: Creates the Keyring & signedProof.

File: packages/vda-sbt-client/src/blockchain/config.ts (hunk 1 above)
Comment (ITStar10) [reply packages/vda-sbt-client/src/blockchain/config.ts:5]: Restored to original address

**Review by tahpot — APPROVED** [review]

**Comment by tahpot** [comment]
@ITStar10 to merge this and resole any conflicts.

**Review by ITStar10 — COMMENTED** [review]
All working.
