### PR TITLE
[verifiable-credential] Save W3C verifiable credential to data, inste…

### LINKED ISSUE #424: [verifiable-credentials] Generated verifiable credential has incorrect data
When creating a Verifiable Credential record for saving into a Verida database, the `data` property is currently storing the raw JSON of the credential properties, rather than the full W3C compmliant Verifiable Credential object.

See https://github.com/verida/verida-js/blob/0927f3c3622c6a059297428ce446197fa67a3de9/packages/verifiable-credentials/src/credentials.ts#L75

### PR DESCRIPTION
**Pull request by tahpot**
Closes #424

### CODE REVIEW

File: packages/verifiable-credentials/src/credentials.ts [hunk 1]
```diff
@@ -68,11 +68,16 @@ export default class Credentials {
 
 		const { data, schema } = createCredentialData
 
+		const {
+			vc,
+			issuer
+		} = await this.buildVerifiableCredential(createCredentialData)
```
Comment (aurelticot) [inline packages/verifiable-credentials/src/credentials.ts:74]: The current:
```ts
const didJwtVc = await this.createCredentialJWT(createCredentialData)

const {
	vc,
	issuer
} = await this.buildVerifiableCredential(createCredentialData)
```

Can be optimised to:
```ts
const {
	vc,
	issuer
} = await this.buildVerifiableCredential(createCredentialData)

const didJwtVc = await this.createVerifiableCredential(vc, issuer)
```

As `createCredentialJWT` execute `buildVerifiableCredential` internally, so `buildVerifiableCredential` is currently done twice.

**Review by aurelticot — APPROVED** [review]

**Comment by aurelticot** [comment]
Aiming to be merged and published in a `4.x`
